<a href="https://colab.research.google.com/github/NevarManisha/NASSCOM/blob/main/WEEK%202/Pandas_Exercise.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [38]:
import pandas as pd
import numpy as np

print("--- Intermediate Pandas Exercise ---")
print("Complete each task by writing the requested Pandas code.")
print("------------------------------------")

# ==========================================================
# Task 1: Basic Pandas Functions and Converting Arrays to DataFrames
# ==========================================================
print("\n--- Task 1: Basic Pandas Functions and Converting Arrays to DataFrames ---")

# 1.1 Create a Pandas Series
s1_1 = pd.Series([10, 20, 30, 40, 50])

# 1.2 Create a 3x4 NumPy array with random integers
np.random.seed(42)   # For reproducibility
np_array1_2 = np.random.randint(1, 101, size=(3, 4))

# 1.3 Convert NumPy array to DataFrame
df1_3 = pd.DataFrame(np_array1_2, columns=["A", "B", "C", "D"])

print("\nSeries:")
print(s1_1)

print("\nNumPy Array:")
print(np_array1_2)

print("\nDataFrame:")
print(df1_3)

# ==========================================================
# Task 2: Synthetic Data Generation for Practice
# ==========================================================
print("\n--- Task 2: Synthetic Data Generation for Practice ---")

dates = pd.date_range("2023-01-01", periods=100)

df_sales = pd.DataFrame({
    "Date": dates,
    "Region": np.random.choice(["East", "West", "North", "South"], size=100),
    "Product": np.random.choice(["Laptop", "Mouse", "Keyboard", "Monitor"], size=100),
    "Sales": np.random.randint(100, 1001, size=100),
    "Quantity": np.random.randint(1, 11, size=100)
})

# Introduce NaN values
sales_nan_idx = np.random.choice(df_sales.index, size=5, replace=False)
quantity_nan_idx = np.random.choice(df_sales.index, size=3, replace=False)

df_sales.loc[sales_nan_idx, "Sales"] = np.nan
df_sales.loc[quantity_nan_idx, "Quantity"] = np.nan

print(df_sales.head())

# ==========================================================
# Task 3: Indexing and Slicing in DataFrames
# ==========================================================
print("\n--- Task 3: Indexing and Slicing in DataFrames ---")

# 3.1 Select Region and Sales columns
df3_1 = df_sales[["Region", "Sales"]]

# 3.2 Rows where Product is Laptop
df3_2 = df_sales[df_sales["Product"] == "Laptop"]

# 3.3 Region is East AND Sales > 500
df3_3 = df_sales[
    (df_sales["Region"] == "East") &
    (df_sales["Sales"] > 500)
]

# 3.4 Sales value for first Monitor entry
monitor_rows = df_sales[df_sales["Product"] == "Monitor"]

if not monitor_rows.empty:
    first_monitor_index = monitor_rows.index[0]
    val3_4 = df_sales.loc[first_monitor_index, "Sales"]
else:
    val3_4 = None

print("\nTask 3.1")
print(df3_1.head())

print("\nTask 3.2")
print(df3_2.head())

print("\nTask 3.3")
print(df3_3.head())

print("\nTask 3.4")
print(val3_4)

# ==========================================================
# Task 4: Data Cleaning (Handling Missing Values)
# ==========================================================
print("\n--- Task 4: Data Cleaning (Handling Missing Values) ---")

# 4.1 Missing values count
missing_counts4_1 = df_sales.isnull().sum()

# 4.2 Fill missing Sales values with mean
df4_2_filled = df_sales.copy()
sales_mean = df4_2_filled["Sales"].mean()
df4_2_filled["Sales"] = df4_2_filled["Sales"].fillna(sales_mean)

# 4.3 Drop rows with any missing values
df4_3_dropped = df_sales.dropna()

print("\nMissing Values:")
print(missing_counts4_1)

print("\nFilled Sales DataFrame:")
print(df4_2_filled.head())

print("\nDropped Missing Rows:")
print(df4_3_dropped.head())

# ==========================================================
# Task 5: Data Manipulation (Columns, Sorting, Grouping)
# ==========================================================
print("\n--- Task 5: Data Manipulation (Columns, Sorting, Grouping) ---")

# 5.1 Create Total_Revenue column
df_sales["Total_Revenue"] = df_sales["Sales"] * df_sales["Quantity"]

# 5.2 Sort by Date ascending and Sales descending
df5_2_sorted = df_sales.sort_values(
    by=["Date", "Sales"],
    ascending=[True, False]
)

# 5.3 Group by Region and sum Sales & Quantity
df5_3_grouped_region = df_sales.groupby("Region")[["Sales", "Quantity"]].sum()

# 5.4 Group by Product and average Sales
df5_4_grouped_product = df_sales.groupby("Product")["Sales"].mean()

print("\nDataFrame with Total_Revenue:")
print(df_sales.head())

print("\nSorted DataFrame:")
print(df5_2_sorted.head())

print("\nGrouped by Region:")
print(df5_3_grouped_region)

print("\nAverage Sales by Product:")
print(df5_4_grouped_product)


--- Intermediate Pandas Exercise ---
Complete each task by writing the requested Pandas code.
------------------------------------

--- Task 1: Basic Pandas Functions and Converting Arrays to DataFrames ---

Series:
0    10
1    20
2    30
3    40
4    50
dtype: int64

NumPy Array:
[[ 52  93  15  72]
 [ 61  21  83  87]
 [ 75  75  88 100]]

DataFrame:
    A   B   C    D
0  52  93  15   72
1  61  21  83   87
2  75  75  88  100

--- Task 2: Synthetic Data Generation for Practice ---
        Date Region  Product  Sales  Quantity
0 2023-01-01  South    Mouse  624.0       1.0
1 2023-01-02  South  Monitor  259.0       9.0
2 2023-01-03  North   Laptop  938.0       6.0
3 2023-01-04   West  Monitor  798.0       3.0
4 2023-01-05   East   Laptop  342.0       4.0

--- Task 3: Indexing and Slicing in DataFrames ---

Task 3.1
  Region  Sales
0  South  624.0
1  South  259.0
2  North  938.0
3   West  798.0
4   East  342.0

Task 3.2
         Date Region Product  Sales  Quantity
2  2023-01-03  North  Lap